# Generated by Django 5.2.6 on 2025-09-16 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the man-page (e.g., 'getent')", max_length=255)),
                ('section', models.CharField(help_text="Man page section (e.g., '1', '2', '3')", max_length=10)),
                ('title', models.CharField(help_text='Full title of the man-page', max_length=500)),
                ('source_path', models.CharField(help_text='Path to the original source file', max_length=1000)),
                ('license', models.CharField(blank=True, help_text='License information', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_tag', models.CharField(help_text="Version tag (e.g., '6.9')", max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'section'], name='accounts_do_name_24b1d5_idx'), models.Index(fields=['version_tag'], name='accounts_do_version_88d872_idx')],
                'unique_together': {('name', 'section', 'version_tag')},
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(help_text="Section name (e.g., 'NAME', 'SYNOPSIS')", max_length=100)),
                ('anchor', models.CharField(help_text='Anchor identifier for the chunk', max_length=200)),
                ('text', models.TextField(help_text='The actual text content of the chunk')),
                ('token_count', models.PositiveIntegerField(help_text='Number of tokens in the text')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='accounts.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'section_name'], name='accounts_ch_documen_227a9c_idx'), models.Index(fields=['anchor'], name='accounts_ch_anchor_e38611_idx'), models.Index(fields=['token_count'], name='accounts_ch_token_c_3f162d_idx')],
            },
        ),
    ]
