# Generated by Django 5.2.6 on 2025-09-16 13:42

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_document_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector', null=True),
        ),
    ]
