# Generated by Django 5.2.6 on 2025-09-16 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name of the man-page (e.g., 'getent')", max_length=255)),
                ('section', models.CharField(help_text="Man page section (e.g., '1', '2', '3')", max_length=10)),
                ('title', models.CharField(help_text='Full title of the man-page', max_length=1000)),
                ('source_path', models.CharField(help_text='Path to the original source file', max_length=1000)),
                ('license', models.CharField(blank=True, help_text='License information', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_tag', models.CharField(help_text="Version tag (e.g., '6.9')", max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'section'], name='search_docu_name_a3dc7c_idx'), models.Index(fields=['version_tag'], name='search_docu_version_1a0a4a_idx')],
                'unique_together': {('name', 'section', 'version_tag')},
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(help_text="Section name (e.g., 'NAME', 'SYNOPSIS')", max_length=100)),
                ('anchor', models.CharField(help_text='Anchor identifier for the chunk', max_length=200)),
                ('text', models.TextField(help_text='The actual text content of the chunk')),
                ('token_count', models.PositiveIntegerField(help_text='Number of tokens in the text')),
                ('qdrant_id', models.CharField(blank=True, help_text='Qdrant vector ID', max_length=100, null=True)),
                ('embedding_model', models.CharField(default='jinaai/jina-embeddings-v2-small-en', help_text='Embedding model used', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='search.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'section_name'], name='search_chun_documen_909d04_idx'), models.Index(fields=['anchor'], name='search_chun_anchor_ae4a6e_idx'), models.Index(fields=['token_count'], name='search_chun_token_c_9a38fd_idx'), models.Index(fields=['qdrant_id'], name='search_chun_qdrant__c4935d_idx')],
            },
        ),
    ]
