# Generated by Django 5.2.6 on 2025-09-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_evaluationquery_evaluationrun_evaluationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if evaluation failed', null=True),
        ),
    ]
